### ISSUE TITLE
[Kirkstone] Raspberry Pi CM3 Uboot bootup issue

### ISSUE THREAD

**Issue by RajasJoshi** [agherzan/meta-raspberrypi#1094]
Hi All,

I have been trying to build a core-image-base image for my Raspberry Pi CM3. The Yocto branch I am trying to build on is Kirkstone, the Kernel version is 5.15.34 and the uboot version is 2022.1. I observed that when I built my image without uboot(Without     RPI_USE_U_BOOT = "1"), the board is able to successfully boot and show console debugs(enable_uart=1). But when I added Uboot in my build(RPI_USE_U_BOOT = "1"), the board showed no response on the console and even the activity led was OFF. I am a building using kas and the yaml is as below.

```YAML
[header:
  version: 8

machine: raspberrypi-cm3
distro: poky
target:
  - core-image-base

repos:
  meta-raspberry:

  poky:
    url: https://git.yoctoproject.org/git/poky
    path: layers/poky
    refspec: kirkstone
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: http://git.openembedded.org/meta-openembedded
    path: layers/meta-openembedded
    refspec: kirkstone
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-perl:

bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""
local_conf_header:
  rpi-specific: |
    IMAGE_FSTYPES = "wic ext4.gz"
    RPI_USE_U_BOOT = "1"
    ENABLE_UART = "1"
    PREFERRED_VERSION_linux-raspberrypi = "5.15.%"
  reduce_diskspace: |
    INHERIT += "rm_work"
  standard: |
    CONF_VERSION = "2"
    PACKAGE_CLASSES = "package_deb"
    SDKMACHINE = "x86_64"
    USER_CLASSES = "buildstats"
    PATCHRESOLVE = "noop"
  debug-tweaks: |
    EXTRA_IMAGE_FEATURES = "debug-tweaks"
  diskmon: |
    BB_DISKMON_DIRS = "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
]
```

Do I need to make any specific changes for it to work on CM3?
Thanks in advance
