### ISSUE TITLE
RPi Zero W won't boot with either core-image-base or rpi-test-image

### ISSUE THREAD

**Issue by dev-sda1** [agherzan/meta-raspberrypi#1356]
**Description**
Building the rpi-test-image or core-image-base with poky as the distro seems to result in an unbootable image for me on a Raspberry Pi Zero W (1st Gen). The ACT LED will flicker a few times before ending up staying a solid green. Connecting a UART probe to GPIO with the Raspberry Pi Debug Probe shows it getting stuck around 9 seconds into the kernel boot process.

Screen output: https://pastebin.com/Z3aBcDLb

**Steps to reproduce the issue:**
1. Build a Raspberry Pi Zero W image with the machine ``raspberrypi0-wifi``, with distro ``poky`` and either target ``core-image-base`` or ``rpi-test-image`` (In both instances I used kas)
2. Flash the resulting rpi-sdimg file to an SD Card
3. Boot Raspberry Pi Zero W with UART probes attached and watch it freeze around 9s in.

**Describe the results you received:**
The image fails to finish booting.

**Describe the results you expected:**
The kernel to boot completely, and land me at the tty login screen.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have attempted with both kirkstone and scarthgap branches of the repos, and neither made a difference.

Kas YML file:
```yml
header:
  version: 1

distro: poky
machine: raspberrypi0-wifi
target: core-image-base

repos:
  meta-pyxl:

  poky:
    url: https://git.yoctoproject.org/poky
    branch: kirkstone
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    path: layers/meta-openembedded
    branch: kirkstone
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-multimedia:

  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi
    path: layers/meta-raspberrypi
    branch: kirkstone

bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH= "${TOPDIR}"
    BBFILES ?= ""
local_conf_header:
  base: |
    CONF_VERSION="2"
    LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"
    IMAGE_FSTYPES="tar.xz ext3 rpi-sdimg wic wic.bmap"

    RPI_KERNEL_DEVICETREE_OVERLAYS:append = " \
    overlays/vc4-kms-dpi-hyperpixel4.dtbo \
    "

    RPI_EXTRA_CONFIG:append = " \n\
    dtoverlay=vc4-kms-dpi-hyperpixel4\n \
    dtoverlay=disable-bt\n\
    enable_uart=1\n\
    uart_2ndstage=1\n\
    "
```

**Additional details (revisions used, host distro, etc.):**
Ubuntu 23.10
Kas 4.2
